# Generated by Django 5.1.4 on 2024-12-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_value', models.FloatField()),
                ('second_value', models.FloatField()),
                ('result', models.FloatField()),
            ],
        ),
    ]
